version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine_board
      MYSQL_ROOT_HOST: '%'  # Разрешаем подключение с любого хоста
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql  # Используем имя сервиса как хост
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: redmine_board
      DB_PORT: 3306
      REDMINE_URL: https://helpdesk.fenix-it.ru/
      TRACKER_URL: https://tracker.fenix-it.ru/
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: